name: Sistema Eso
services:
  postgres:
    image: postgres:15
    container_name: eso_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eso_db
    ports:
      - "5433:5432"